### ISSUE TITLE
Models Tests: Get region under test

### ISSUE THREAD

**Issue by douglasdennis** [Hoboson02/cs362-coad-resources#6]
Model `region` needs to be under test.

## Acceptance Criteria:
* Test existence of all model attributes (Step 2.4)
* All associations are tested (Step 2.6)
* The following attributes are **not** tested for:
    * created_at
    * updated_at
    * ids

**Comment by AlliLEarl** [comment]
All of the tests are passing, so I am going to close this issue out.
